import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const templatesDir = join(__dirname, '..', 'templates');

/**
 * Generate TypeScript definitions for storepix config
 * @param {Object} options
 */
export async function types(options) {
  const targetDir = resolve(options.dir);

  console.log('\n  storepix - Generating TypeScript Definitions\n');

  // Check if directory exists
  if (!existsSync(targetDir)) {
    console.log(`  Error: Directory not found: ${targetDir}`);
    console.log('  Run "npx storepix init" first to create a project.\n');
    process.exit(1);
  }

  // Try to determine template from config or version file
  let templateName = 'default';

  // Check version file for template info
  const versionPath = join(targetDir, '.storepix-version.json');
  if (existsSync(versionPath)) {
    try {
      const versionInfo = JSON.parse(readFileSync(versionPath, 'utf-8'));
      templateName = versionInfo.template || 'default';
    } catch (e) {
      // Ignore parse errors
    }
  }

  // Load template schema
  let schema = null;
  const projectSchemaPath = join(targetDir, 'templates', templateName, 'schema.json');
  const packageSchemaPath = join(templatesDir, templateName, 'schema.json');

  if (existsSync(projectSchemaPath)) {
    try {
      schema = JSON.parse(readFileSync(projectSchemaPath, 'utf-8'));
    } catch (e) {
      // Ignore
    }
  } else if (existsSync(packageSchemaPath)) {
    try {
      schema = JSON.parse(readFileSync(packageSchemaPath, 'utf-8'));
    } catch (e) {
      // Ignore
    }
  }

  // Generate TypeScript definitions
  const dtsContent = generateTypeDefinitions(templateName, schema);

  // Write to project
  const dtsPath = join(targetDir, 'storepix.d.ts');
  writeFileSync(dtsPath, dtsContent);

  console.log(`  Generated: storepix.d.ts`);
  console.log(`  Template: ${templateName}\n`);

  console.log('  Usage in storepix.config.js:');
  console.log('    // @ts-check');
  console.log('    /** @type {import("./storepix.d.ts").StorepixConfig} */');
  console.log('    export default { ... };\n');
}

/**
 * Generate TypeScript definition content
 * @param {string} templateName
 * @param {Object|null} schema
 * @returns {string}
 */
function generateTypeDefinitions(templateName, schema) {
  const templateSpecificFields = getTemplateSpecificTypes(templateName);

  return `// Auto-generated by storepix - regenerate with "npx storepix types"
// Template: ${templateName}

/** Device identifiers */
export type StorepixDevice =
  | 'iphone-6.9' | 'iphone-6.7' | 'iphone-6.5' | 'iphone-6.3' | 'iphone-6.1' | 'iphone-5.5' | 'iphone-4.7'
  | 'ipad-13' | 'ipad-12.9' | 'ipad-11'
  | 'android-phone' | 'android-tablet-7' | 'android-tablet-10' | 'android-wear';

/** Screenshot theme */
export type StorepixThemeMode = 'light' | 'dark';

/** Headline layout position */
export type StorepixLayout = 'top' | 'bottom';

/** Status bar style */
export type StorepixStatusBarStyle = 'light' | 'dark' | 'auto';

/** Theme configuration */
export interface StorepixTheme {
  /** Primary accent color (hex format, e.g., '#007AFF') */
  primary?: string;
  /** Font family name */
  font?: string;
  /** Background color override (minimal template) */
  background?: string;
  /** Home indicator color for light theme */
  homeIndicatorLight?: string;
  /** Home indicator color for dark theme */
  homeIndicatorDark?: string;
}

/** Status bar configuration */
export interface StorepixStatusBar {
  /** Enable status bar overlay */
  enabled?: boolean;
  /** Time to display (e.g., '9:41') */
  time?: string;
  /** Battery percentage (0-100) */
  battery?: number;
  /** Show battery percentage text */
  showBatteryPercent?: boolean;
  /** Status bar icon style */
  style?: StorepixStatusBarStyle;
}

/** Output configuration */
export interface StorepixOutput {
  /** Output directory (relative to config) */
  dir?: string;
  /** Output format */
  format?: 'png';
}

/** Base screenshot configuration (all templates) */
export interface StorepixScreenshotBase {
  /** Unique identifier for this screenshot (used in output filename) */
  id: string;
  /** Path to source screenshot image (relative to config directory) */
  source: string;
  /** Color theme for background and text */
  theme?: StorepixThemeMode;
  /** Position of headline relative to device */
  layout?: StorepixLayout;
  /** Main marketing headline */
  headline?: string;
  /** Secondary text below headline */
  subheadline?: string;
}

${templateSpecificFields}

/** Localization overrides */
export interface StorepixLocales {
  [locale: string]: {
    [screenshotId: string]: Partial<StorepixScreenshot>;
  };
}

/** Main storepix configuration */
export interface StorepixConfig {
  /** Template to use (from ./templates/) */
  template?: string;
  /** Output settings */
  output?: StorepixOutput;
  /** Device sizes to generate */
  devices?: StorepixDevice[];
  /** Theme customization (injected as CSS variables) */
  theme?: StorepixTheme;
  /** Status bar injection configuration */
  statusBar?: StorepixStatusBar;
  /** Screenshot definitions */
  screenshots: StorepixScreenshot[];
  /** Localization overrides by locale and screenshot ID */
  locales?: StorepixLocales;
}

declare const config: StorepixConfig;
export default config;
`;
}

/**
 * Get template-specific type definitions
 * @param {string} templateName
 * @returns {string}
 */
function getTemplateSpecificTypes(templateName) {
  switch (templateName) {
    case 'photo':
      return `/** Screenshot configuration for 'photo' template */
export interface StorepixScreenshot extends StorepixScreenshotBase {
  /** Background image path (relative to config directory) */
  background?: string;
  /** Custom content fields for data-storepix bindings */
  [key: string]: string | number | boolean | undefined;
}`;

    case 'panorama':
      return `/** Screenshot configuration for 'panorama' template */
export interface StorepixScreenshot extends StorepixScreenshotBase {
  /** Number of slices for panorama mode (1 = single, 2+ = panorama) */
  slices?: number;
  /** Per-slice headlines (panorama mode only, when slices > 1) */
  headlines?: string[];
  /** Per-slice subheadlines (panorama mode only, when slices > 1) */
  subheadlines?: string[];
  /** Custom content fields for data-storepix bindings */
  [key: string]: string | number | boolean | string[] | undefined;
}`;

    default:
      return `/** Screenshot configuration for '${templateName}' template */
export interface StorepixScreenshot extends StorepixScreenshotBase {
  /** Custom content fields for data-storepix bindings */
  [key: string]: string | number | boolean | undefined;
}`;
  }
}
